#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use Term::ANSIColor;
use Text::ANSI::WideUtil qw(ta_mbwrap);
use Term::ReadKey;
# use Text::Wrap;

my $NICK = 'hanavi';

# Set some color variables
my $C_DEF = color('reset');
my $C_NICKBRACE = color('red');
my $C_TIMEBRACE = color('red');
my $C_NICK = color('cyan');
my $C_TIME = color('magenta');
my $C_DATE = color('bold blue');
my $C_MYNICK = color('bold red');
my $C_URL = color('green');
my $C_NICKHILITE = color('white on_bright_blue');
my $C_HILITE = color('white on_bright_red');
my $C_INFO = color('bright_blue');
my $C_CHANNEL = color('yellow');

my @matchwords = ("ai4lx", "hanavi", "kc4aaa");

while (<>)
{

    my $line = $_;
    my $date = $1 if $line =~ /^([0-9]{10})/;
    my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime($date);
    $year += 1900;
    my $newdate = sprintf "${C_TIME}%02d:%02d:%02d${C_DEF}",$hour,$min,$sec;

    # Format the time
    $line =~ s/^([0-9]{10})/${C_TIMEBRACE}[ ${C_DEF}$newdate ${C_TIMEBRACE}]${C_DEF}/;

    #Format my nick
    $line =~ s/$NICK/ ${C_MYNICK}${NICK}${C_DEF}/g;

    my $hilite = 0;
    foreach my $matchword (@matchwords)
    {
        if ($line =~ m/$matchword/i)
        {
            if ($hilite == 0)
            {
                $line =~ s#<(.*?)>#${C_NICKBRACE}<${C_NICKHILITE}$1${C_DEF}${C_NICKBRACE}>${C_DEF}#;
            }
            $line =~ s#($matchword)#${C_HILITE}$1${C_DEF}#gi;
            $hilite = 1;
        }
    }
    if ($hilite == 0)
    {
        $line =~ s#<(.*?)>#${C_NICKBRACE}<${C_NICK}$1${C_NICKBRACE}>${C_DEF}# ;
    }

    $line =~ s#(-!-.*)#${C_INFO}$1${C_DEF}# if $line =~ m/-!-/;
    $line =~ s#(\bhttp[s]?://[^\s]+)#${C_URL}$1${C_DEF}#;
    $line =~ s/(#[^\s]+)/${C_CHANNEL}$1${C_DEF}/g;

    my ($wchar, $hchar, $wpixels, $hpixels) = GetTerminalSize();
    $Text::Wrap::columns = $wchar-5;
    print(color('reset'));
    # print $line;
    print ta_mbwrap($line, $wchar-2);

}
